/*
  -------------------------------------------------------------------------
  🔒 SMART KITCHEN V2: ARCHITECTURE UPGRADE
  -------------------------------------------------------------------------
  Objetivo: Transformar el modelo "Lista Plana" a "Grafo Jerárquico" (MRP).
  Fecha: Febrero 2026
  
  ESTE SCRIPT ES SEGURO DE CORRER:
  1. No borra datos, los migra.
  2. Es idempotente (usa IF NOT EXISTS).
  -------------------------------------------------------------------------
*/

-- 1. Definir Tipos de Receta
-- Una receta ahora puede ser:
-- 'FINAL_PRODUCT': Lo que se vende (e.j. Torta Selva Negra).
-- 'COMPONENT': Parte de otro (e.j. Bizcocho Genoise).
DO $$ BEGIN
    CREATE TYPE recipe_type AS ENUM ('PRODUCTO_FINAL', 'COMPONENTE_BASE', 'PREPARACION_INTERMEDIA');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Mejorar la Tabla de Recetas (Nodos)
ALTER TABLE public.recetas 
ADD COLUMN IF NOT EXISTS tipo recipe_type DEFAULT 'PRODUCTO_FINAL',
ADD COLUMN IF NOT EXISTS rendimiento_base_g NUMERIC DEFAULT 0; -- Peso total de la salida

-- 3. Crear la Tabla Maestra de Composición (Aristas del Grafo)
-- Esta tabla reemplaza a 'receta_ingredientes' y permite recursividad.
CREATE TABLE IF NOT EXISTS public.recipe_composition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_recipe_id UUID NOT NULL REFERENCES public.recetas(id) ON DELETE CASCADE,
  
  -- Polimorfismo: Una receta está hecha de Ingredientes O de otras Recetas
  child_ingredient_id UUID REFERENCES public.ingredientes(id) ON DELETE RESTRICT,
  child_recipe_id UUID REFERENCES public.recetas(id) ON DELETE RESTRICT,
  
  cantidad NUMERIC(10,2) NOT NULL,
  unidad TEXT NOT NULL DEFAULT 'g',
  notas TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraint de Integridad: O es Ingrediente O es Receta, no ambos
  CONSTRAINT chk_composition_target CHECK (
    (child_ingredient_id IS NOT NULL AND child_recipe_id IS NULL) OR
    (child_ingredient_id IS NULL AND child_recipe_id IS NOT NULL)
  )
);

-- 4. Habilitar RLS en la nueva tabla
ALTER TABLE public.recipe_composition ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad (Iguales a las anteriores)
CREATE POLICY "Public Read Composition" ON public.recipe_composition FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Admin Write Composition" ON public.recipe_composition FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'admin')
);

-- 5. 🔄 MIGRACIÓN DE DATOS REVERSIVA
-- Copiar todo lo que había en la tabla vieja a la nueva estructura
INSERT INTO public.recipe_composition (parent_recipe_id, child_ingredient_id, cantidad, unidad, notas)
SELECT 
    receta_id, 
    ingrediente_id, 
    cantidad, 
    'g', -- Asumimos 'g' por defecto, ajustar luego si es necesario
    notas
FROM public.receta_ingredientes
WHERE NOT EXISTS (
    SELECT 1 FROM public.recipe_composition rc 
    WHERE rc.parent_recipe_id = receta_ingredientes.receta_id 
    AND rc.child_ingredient_id = receta_ingredientes.ingrediente_id
);

-- 6. (Opcional) Crear una vista para facilitar consultas
-- Esta vista "aplana" la composición para ver nombres fácilmente
CREATE OR REPLACE VIEW public.v_recipe_details AS
SELECT 
    rc.id,
    rc.parent_recipe_id,
    p.nombre as receta_padre,
    CASE 
        WHEN rc.child_ingredient_id IS NOT NULL THEN 'MATERIAL'
        ELSE 'SUB-RECETA'
    END as tipo,
    COALESCE(i.nombre, r_child.nombre) as nombre_item,
    rc.cantidad,
    rc.unidad,
    COALESCE(i.precio, 0) as costo_unitario_estimado -- Solo para ingredientes por ahora
FROM public.recipe_composition rc
JOIN public.recetas p ON rc.parent_recipe_id = p.id
LEFT JOIN public.ingredientes i ON rc.child_ingredient_id = i.id
LEFT JOIN public.recetas r_child ON rc.child_recipe_id = r_child.id;

-- Notificación final
DO $$ BEGIN
    RAISE NOTICE '✅ Migración a Modelo Grafo completada exitosamente.';
END $$;
